# Generated by Django 4.2.11 on 2026-03-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, choices=[('visual_arts', 'Visual Arts'), ('design', 'Design'), ('animation', 'Animation'), ('photography', 'Photography'), ('filmmaking', 'Filmmaking'), ('music', 'Music'), ('writing', 'Writing'), ('tech', 'Technology'), ('mixed_media', 'Mixed Media'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_covers/'),
        ),
    ]
