# Generated by Django 4.2.11 on 2026-03-29 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_portfolio_category_portfolio_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('collaboration_request', 'Collaboration Request'), ('collaboration_accepted', 'Collaboration Accepted'), ('collaboration_rejected', 'Collaboration Rejected'), ('project_update', 'Project Update'), ('message', 'Message'), ('profile_view', 'Profile View'), ('mentorship_request', 'Mentorship Request'), ('mentorship_accepted', 'Mentorship Accepted'), ('mentorship_rejected', 'Mentorship Rejected')], max_length=50),
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('skills_to_learn', models.TextField(blank=True, help_text='Comma-separated skills mentee wants to learn', null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('mentor', 'mentee')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='related_mentorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mentorshiprequest'),
        ),
    ]
