# Generated by Django 4.2.11 on 2026-03-29 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
