# Generated by Django 4.2.11 on 2026-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_creativework_liked_by_alter_creativework_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
