# Generated by Django 4.2.11 on 2026-03-29 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_portfolio_total_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'Status Change'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('creation', 'Creation'), ('other', 'Other')], max_length=50)),
                ('entity_type', models.CharField(help_text='Model name, e.g., Project, Collaboration', max_length=50)),
                ('entity_id', models.PositiveIntegerField()),
                ('details', models.TextField(help_text='JSON or text details of the change')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
