# Generated by Django 4.2.11 on 2026-03-29 20:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='file',
            field=models.FileField(upload_to='creative_works/', validators=[core.models.validate_file_size]),
        ),
    ]
